# Generated by Django 4.0 on 2022-07-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_entrega'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrega',
            new_name='Entregable',
        ),
    ]
